import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { requireRequestSession } from "@/lib/auth/access";
import { forbidden, requireOwnerManagedCompany } from "@/lib/owner-management/access";
const patchSchema=z.object({transactionDate:z.string().datetime().nullable().optional(),postingDate:z.string().datetime().nullable().optional(),description:z.string().max(10000).optional(),amount:z.coerce.number().positive().max(100000000).optional(),partnerId:z.string().nullable().optional(),status:z.enum(["MATCHED","UNMATCHED","INVALID","DUPLICATE","REVIEW"]).optional()});const voidSchema=z.object({reason:z.string().min(3).max(2000)});
async function base(request:NextRequest,params:Promise<{companyId:string;revenueId:string}>){const s=await requireRequestSession(request);if(s instanceof NextResponse)return[null,null,null]as const;const{companyId,revenueId}=await params;if(!await requireOwnerManagedCompany(s,companyId))return[s,null,null]as const;return[s,companyId,await prisma.ownerManagedRevenue.findFirst({where:{id:revenueId,companyId}})]as const;}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{companyId:string;revenueId:string}>}){const[s,c,row]=await base(request,params);if(!s||!c||!row)return forbidden();const p=patchSchema.safeParse(await request.json());if(!p.success)return NextResponse.json({success:false,error:"Invalid revenue data"},{status:400});if(p.data.partnerId){const partner=await prisma.ownerManagedPartner.findFirst({where:{id:p.data.partnerId,companyId:c,isActive:true},select:{id:true}});if(!partner)return NextResponse.json({success:false,error:"Invalid partner"},{status:400});}const updated=await prisma.$transaction(async tx=>{const x=await tx.ownerManagedRevenue.update({where:{id:row.id},data:{...p.data,amount:p.data.amount===undefined?undefined:p.data.amount.toFixed(3),transactionDate:p.data.transactionDate===undefined?undefined:p.data.transactionDate?new Date(p.data.transactionDate):null,postingDate:p.data.postingDate===undefined?undefined:p.data.postingDate?new Date(p.data.postingDate):null}});await tx.auditLog.create({data:{userId:s.id,companyId:c,action:"UPDATE_OWNER_MANAGED_REVENUE",module:"owner_management",resourceId:x.id,resourceType:"OwnerManagedRevenue"}});return x});return NextResponse.json({success:true,data:updated});}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{companyId:string;revenueId:string}>}){const[s,c,row]=await base(request,params);if(!s||!c||!row)return forbidden();const p=voidSchema.safeParse(await request.json());if(!p.success)return NextResponse.json({success:false,error:"Void reason is required"},{status:400});await prisma.$transaction(async tx=>{await tx.ownerManagedRevenue.update({where:{id:row.id},data:{status:"VOIDED",voidedAt:new Date(),voidedById:s.id,voidReason:p.data.reason}});await tx.auditLog.create({data:{userId:s.id,companyId:c,action:"VOID_OWNER_MANAGED_REVENUE",module:"owner_management",resourceId:row.id,resourceType:"OwnerManagedRevenue"}})});return NextResponse.json({success:true});}
