import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Prisma } from "@prisma/client";
import { ExpenseActions } from "@/components/owner-management/expense-actions";
import { getSession } from "@/lib/auth/session";
import { requireOwnerManagedCompany } from "@/lib/owner-management/access";
import { prisma } from "@/lib/db";
const PAGE_SIZE = 25; const date = (value?: string) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00.000Z`) : undefined;
export default async function OwnerManagedExpensesPage({ params, searchParams }: { params: Promise<{ companyId: string }>; searchParams: Promise<{ from?: string; to?: string; page?: string }> }) {
  const { companyId } = await params; const search = await searchParams; const session = await getSession(); if (!session) redirect("/login"); if (!await requireOwnerManagedCompany(session, companyId)) notFound(); const from = date(search.from), to = date(search.to); if (to) to.setUTCHours(23, 59, 59, 999); const page = Math.max(1, Number(search.page) || 1); const where: Prisma.OwnerManagedExpenseWhereInput = { companyId, deletedAt: null, ...(from || to ? { invoiceDate: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {}) }; const [expenses, total, aggregate] = await Promise.all([prisma.ownerManagedExpense.findMany({ where, include: { partner: { select: { name: true, mid: true } } }, orderBy: [{ invoiceDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }), prisma.ownerManagedExpense.count({ where }), prisma.ownerManagedExpense.aggregate({ where, _sum: { amount: true } })]); const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const query = new URLSearchParams(); if (search.from) query.set("from", search.from); if (search.to) query.set("to", search.to); const href = (next: number) => `?${new URLSearchParams({ ...Object.fromEntries(query), page: String(next) })}`;
  return <div className="page-container space-y-5" dir="rtl"><header><h1 className="text-2xl font-bold">المصروفات</h1><p className="text-sm text-muted-foreground">الإجمالي للفترة: {Number(aggregate._sum.amount ?? 0).toFixed(3)} د.ك</p></header><form className="section-card flex flex-wrap gap-3"><label>من<input className="ms-2 rounded border p-2" name="from" type="date" defaultValue={search.from} /></label><label>إلى<input className="ms-2 rounded border p-2" name="to" type="date" defaultValue={search.to} /></label><button className="rounded bg-primary px-4 py-2 text-primary-foreground">تصفية</button></form><div className="section-card overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b"><th>التاريخ</th><th>الشريك</th><th>MID</th><th>المبلغ</th><th>ملاحظات</th><th>الإجراءات</th></tr></thead><tbody>{expenses.length ? expenses.map((row) => <tr key={row.id} className="border-b"><td>{row.invoiceDate.toLocaleDateString("en-CA")}</td><td>{row.partner.name}</td><td dir="ltr">{row.partner.mid}</td><td>{Number(row.amount).toFixed(3)}</td><td>{row.notes ?? "—"}</td><td><ExpenseActions companyId={companyId} expenseId={row.id} amount={Number(row.amount)} invoiceDate={row.invoiceDate.toLocaleDateString("en-CA")} notes={row.notes} imageUrl={row.imageUrl} /></td></tr>) : <tr><td className="p-6 text-center text-muted-foreground" colSpan={6}>لا توجد مصروفات للفترة.</td></tr>}</tbody></table></div><nav className="flex items-center justify-between"><Link className="rounded border px-3 py-2" href={page > 1 ? href(page - 1) : href(1)}>السابق</Link><span>صفحة {page} من {pages}</span><Link className="rounded border px-3 py-2" href={page < pages ? href(page + 1) : href(pages)}>التالي</Link></nav><Link className="text-primary underline" href={`/dashboard/companies/${companyId}/owner-management`}>العودة</Link></div>;
}
