"use client";

import { useParams } from "next/navigation";
import { useState } from "react";

type PreviewRow = { pageNumber: number; transactionDate?: string; postingDate?: string; description: string; amount: string; mid: string | null; transactionReference: string | null; partnerName?: string; rawRowText: string; status: string };
type Preview = { token: string; pageCount: number; rows: PreviewRow[]; summary: Record<string, number> };
type PreviewResponse = { success?: boolean; data?: Preview; error?: string; details?: string };

async function responseJson(response: Response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return { error: text || `HTTP ${response.status}` }; } }

export default function OwnerManagedImportPage() {
  const { companyId } = useParams<{ companyId: string }>();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function previewFile() { if (!file) return; setLoading(true); setMessage(""); try { const form = new FormData(); form.append("file", file); const response = await fetch(`/api/owner-management/companies/${companyId}/statement/preview`, { method: "POST", body: form }); const data = await responseJson(response) as PreviewResponse; if (!response.ok || !data.data) { setMessage(`${data.error ?? "تعذرت المعاينة"}${data.details ? ` — ${data.details}` : ""}`); return; } setPreview(data.data); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذرت المعاينة"); } finally { setLoading(false); } }
  async function confirm() { if (!preview) return; setLoading(true); try { const response = await fetch(`/api/owner-management/companies/${companyId}/statement/confirm`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: preview.token }) }); const data = await responseJson(response) as { savedCount?: number; skippedCount?: number; totalsByPartner?: Record<string, string>; skipped?: Record<string, number>; error?: string }; if (!response.ok) { setMessage(data.error ?? "تعذر الحفظ"); return; } if (!data.savedCount) { setMessage(`لم تُحفظ أي عملية. الأسباب: ${Object.entries(data.skipped ?? {}).map(([reason, count]) => `${reason}: ${count}`).join("، ") || "غير محددة"}`); return; } const totals = Object.entries(data.totalsByPartner ?? {}).map(([name, total]) => `${name}: ${total}`).join("، "); setMessage(`تم حفظ ${data.savedCount} عملية؛ المتجاهل ${data.skippedCount ?? 0}${totals ? ` — ${totals}` : ""}`); window.location.assign(`/dashboard/companies/${companyId}/owner-management/revenues`); } finally { setLoading(false); } }
  const confirmationBlocked = !preview || preview.summary.matched === 0 || preview.summary.invalid / Math.max(preview.summary.total, 1) > 0.2 || preview.rows.every((row) => Number(row.amount) === 0);
  return <div className="page-container max-w-7xl space-y-5" dir="rtl"><div><h1 className="text-2xl font-bold">رفع كشف حساب NBK</h1><p className="text-sm text-muted-foreground">لن تُحفظ أي بيانات قبل تأكيد الاستيراد.</p></div><div className="section-card flex flex-wrap items-center gap-3"><input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><button className="rounded-lg bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50" disabled={!file || loading} onClick={previewFile}>{loading ? "جارٍ الاستخراج…" : "معاينة PDF"}</button></div>{message && <p className="rounded-lg bg-muted p-3 text-sm">{message}</p>}{preview && <section className="space-y-3"><div className="section-card flex justify-between"><span>{preview.pageCount} صفحات</span><span>الإجمالي: {preview.summary.total} · المطابق: {preview.summary.matched} · غير صالح: {preview.summary.invalid}</span><button className="rounded-lg bg-primary px-4 py-2 text-primary-foreground disabled:opacity-50" disabled={loading || confirmationBlocked} onClick={confirm}>تأكيد الاستيراد</button></div><div className="overflow-x-auto section-card"><table className="w-full text-sm"><thead><tr className="border-b text-right"><th>تاريخ العملية</th><th>تاريخ القيد</th><th>الصفحة</th><th>الوصف</th><th>المبلغ</th><th>MID</th><th>المرجع</th><th>الشريك</th><th>الحالة</th><th>النص الخام</th></tr></thead><tbody>{preview.rows.map((row, index) => <tr className="border-b align-top" key={index}><td dir="ltr">{row.transactionDate?.slice(0, 10) ?? "-"}</td><td dir="ltr">{row.postingDate?.slice(0, 10) ?? "-"}</td><td>{row.pageNumber}</td><td className="max-w-sm py-2">{row.description || "-"}</td><td dir="ltr">{row.amount}</td><td dir="ltr">{row.mid ?? "-"}</td><td dir="ltr">{row.transactionReference ?? "-"}</td><td>{row.partnerName ?? "-"}</td><td>{row.status}</td><td><details><summary className="cursor-pointer">عرض النص الخام</summary><p className="mt-2 max-w-md whitespace-pre-wrap break-words">{row.rawRowText}</p></details></td></tr>)}</tbody></table></div></section>}</div>;
}
