import Link from "next/link";
import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth/session";
import { getPartnerFromSession } from "@/lib/owner-management/access";
import { prisma } from "@/lib/db";
const date = (value?: string) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00.000Z`) : undefined;
export default async function PartnerStatementPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  const search = await searchParams; const session = await getSession(); if (!session) redirect("/login"); const partner = await getPartnerFromSession(session); if (!partner) redirect("/dashboard"); const from = date(search.from), to = date(search.to); if (to) to.setUTCHours(23, 59, 59, 999); const period = from || to ? { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } : undefined; const revenueWhere: Prisma.OwnerManagedRevenueWhereInput = { partnerId: partner.id, status: "MATCHED", ...(period ? { transactionDate: period } : {}) }; const expenseWhere: Prisma.OwnerManagedExpenseWhereInput = { partnerId: partner.id, deletedAt: null, ...(period ? { invoiceDate: period } : {}) }; const [revenue, expense] = await Promise.all([prisma.ownerManagedRevenue.aggregate({ where: revenueWhere, _sum: { amount: true } }), prisma.ownerManagedExpense.aggregate({ where: expenseWhere, _sum: { amount: true } })]); const totalRevenue = Number(revenue._sum.amount ?? 0), totalExpense = Number(expense._sum.amount ?? 0);
  return <main dir="rtl" className="min-h-screen bg-muted/30 p-4 md:p-8"><section className="mx-auto max-w-2xl space-y-6"><div><h1 className="text-2xl font-bold">كشف حسابي</h1><p className="text-muted-foreground">MID: <span dir="ltr">{partner.mid}</span></p></div><form className="section-card flex flex-wrap gap-3"><label>من<input className="ms-2 rounded border p-2" name="from" type="date" defaultValue={search.from} /></label><label>إلى<input className="ms-2 rounded border p-2" name="to" type="date" defaultValue={search.to} /></label><button className="rounded bg-primary px-4 py-2 text-primary-foreground">تصفية</button></form><dl className="section-card grid gap-4 sm:grid-cols-3"><div><dt>إجمالي الإيرادات</dt><dd className="text-xl font-bold">{totalRevenue.toFixed(3)}</dd></div><div><dt>إجمالي المصروفات</dt><dd className="text-xl font-bold">{totalExpense.toFixed(3)}</dd></div><div><dt>الصافي</dt><dd className="text-xl font-bold">{(totalRevenue - totalExpense).toFixed(3)}</dd></div></dl><Link className="text-primary underline" href="/partner">العودة للبوابة</Link></section></main>;
}
