"use client";

import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { nanoid } from "nanoid";
import { useLocale } from "@/components/providers/locale-provider";

type Session = { id: string; status: "ACTIVE" | "PAUSED" | "ENDED"; startedAt: string };
type Point = { clientGeneratedId: string; latitude: number; longitude: number; accuracy: number | null; altitude: number | null; heading: number | null; speed: number | null; recordedAt: string };
type TrackingContext = { session: Session | null; tracking: boolean; starting: boolean; locationCount: number; lastLocation: { lat: number; lng: number } | null; error: string | null; startTracking: () => Promise<void>; stopTracking: (password: string) => Promise<{ ok: boolean; code?: string }>; retryTracking: () => Promise<void> };
const Context = createContext<TrackingContext | null>(null);
const toPoint = (position: GeolocationPosition): Point => ({ clientGeneratedId: nanoid(16), latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, altitude: position.coords.altitude, heading: position.coords.heading, speed: position.coords.speed, recordedAt: new Date(position.timestamp).toISOString() });
const geolocationErrorKey = (error: unknown) => {
  const code = typeof error === "object" && error !== null && "code" in error && typeof error.code === "number" ? error.code : 0;
  return ({ 1: "driver.permissionDenied", 2: "driver.positionUnavailable", 3: "driver.positionTimeout" } as Record<number, string>)[code] ?? "driver.positionUnavailable";
};
const trackingApiErrorKey = (status: number, code: unknown, fallback: string) => {
  const key = typeof code === "string" ? code : "";
  const keys: Record<string, string> = { UNAUTHORIZED: "driver.trackingSessionExpired", FORBIDDEN: "driver.accountNotAllowed", INCORRECT_PASSWORD: "driver.incorrectStopPassword", TOO_MANY_ATTEMPTS: "driver.tooManyStopAttempts", PASSWORD_REQUIRED: "driver.stopPasswordRequired", STOP_NOT_AVAILABLE: "driver.stopTrackingFailed", STOP_FAILED: "driver.stopTrackingFailed" };
  return keys[key] ?? ({ 401: "driver.trackingSessionExpired", 403: "driver.accountNotAllowed" }[status] ?? fallback);
};

export function DriverTrackingProvider({ children }: { children: React.ReactNode }) {
  const { t } = useLocale();
  const [session, setSession] = useState<Session | null>(null); const [tracking, setTracking] = useState(false); const [starting, setStarting] = useState(false); const [locationCount, setLocationCount] = useState(0); const [lastLocation, setLastLocation] = useState<{ lat: number; lng: number } | null>(null); const [error, setError] = useState<string | null>(null);
  const sessionRef = useRef<Session | null>(null); const watchRef = useRef<number | null>(null); const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null); const queueRef = useRef<Point[]>([]); const sendingRef = useRef(false);
  const setActiveSession = (value: Session | null) => { sessionRef.current = value; setSession(value); setTracking(Boolean(value)); };
  const stopWatcher = useCallback(() => { if (watchRef.current !== null) navigator.geolocation.clearWatch(watchRef.current); if (intervalRef.current) clearInterval(intervalRef.current); watchRef.current = null; intervalRef.current = null; }, []);
  const flush = useCallback(async () => { const current = sessionRef.current; if (!current || !queueRef.current.length || sendingRef.current) return; sendingRef.current = true; const points = queueRef.current.splice(0); try { const response = await fetch('/api/driver/tracking/location', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: current.id, locations: points }) }); if (!response.ok) queueRef.current.unshift(...points); } catch { queueRef.current.unshift(...points); } finally { sendingRef.current = false; } }, []);
  const beginWatch = useCallback(() => { if (watchRef.current !== null || !sessionRef.current || !navigator.geolocation) return; watchRef.current = navigator.geolocation.watchPosition((position) => { const point = toPoint(position); queueRef.current.push(point); setLastLocation({ lat: point.latitude, lng: point.longitude }); setLocationCount((count) => count + 1); if (queueRef.current.length >= 10) void flush(); }, (geolocationError) => setError(t(geolocationErrorKey(geolocationError))), { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 }); intervalRef.current = setInterval(() => { void flush(); }, 30000); }, [flush, t]);
  const restore = useCallback(async () => { try { const response = await fetch('/api/driver/tracking/session/start', { cache: 'no-store' }); const payload: { data?: (Session & { locationCount: number; lastLocation: { lat: number; lng: number } | null }); code?: unknown } = await response.json(); if (response.ok && payload.data) { const active = payload.data; setActiveSession(active); setLocationCount(active.locationCount); setLastLocation(active.lastLocation); } else if (!response.ok) { setError(t(trackingApiErrorKey(response.status, payload.code, 'driver.restoreTrackingFailed'))); } } catch { setError(t('driver.restoreTrackingFailed')); } }, [t]);
  useEffect(() => { void restore(); return stopWatcher; }, [restore, stopWatcher]); useEffect(() => { if (tracking) beginWatch(); }, [tracking, beginWatch]);
  const startTracking = async () => { if (!navigator.geolocation) { setError(t('driver.browserLocationUnsupported')); return; } setStarting(true); setError(null); let locationResolved = false; try { const position = await new Promise<GeolocationPosition>((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 })); locationResolved = true; const point = toPoint(position); const response = await fetch('/api/driver/tracking/session/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ deviceInfo: navigator.userAgent, initialLocation: point }) }); const payload: { success?: boolean; data?: Session; code?: unknown } = await response.json(); if (!response.ok || !payload.success) { setError(t(trackingApiErrorKey(response.status, payload.code, 'driver.trackingStartFailed'))); return; } setActiveSession(payload.data as Session); setLocationCount(1); setLastLocation({ lat: point.latitude, lng: point.longitude }); } catch (trackingError) { setError(t(locationResolved ? 'driver.trackingConnectionError' : geolocationErrorKey(trackingError))); } finally { setStarting(false); } };
  const stopTracking = async (password: string) => { const current = sessionRef.current; if (!current) return { ok: true }; try { const response = await fetch('/api/driver/tracking/session/end', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: current.id, masterPassword: password }) }); if (!response.ok) { const payload: { code?: unknown } = await response.json().catch(() => ({})); setError(t(trackingApiErrorKey(response.status, payload.code, 'driver.stopTrackingFailed'))); return { ok: false, code: typeof payload.code === 'string' ? payload.code : undefined }; } stopWatcher(); await flush(); queueRef.current = []; setActiveSession(null); setLocationCount(0); setLastLocation(null); return { ok: true }; } catch { setError(t('driver.trackingConnectionError')); return { ok: false, code: 'CONNECTION_ERROR' }; } };
  return <Context.Provider value={{ session, tracking, starting, locationCount, lastLocation, error, startTracking, stopTracking, retryTracking: startTracking }}>{children}</Context.Provider>;
}
export function useDriverTracking() { const context = useContext(Context); if (!context) throw new Error('DriverTrackingProvider is required'); return context; }
