"use client";

import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { nanoid } from "nanoid";

type Session = { id: string; status: "ACTIVE" | "PAUSED" | "ENDED"; startedAt: string };
type Point = { clientGeneratedId: string; latitude: number; longitude: number; accuracy: number | null; altitude: number | null; heading: number | null; speed: number | null; recordedAt: string };
type TrackingContext = { session: Session | null; tracking: boolean; starting: boolean; locationCount: number; lastLocation: { lat: number; lng: number } | null; error: string | null; startTracking: () => Promise<void>; stopTracking: (password: string) => Promise<{ ok: boolean; code?: string }>; retryTracking: () => Promise<void> };
const Context = createContext<TrackingContext | null>(null);
const toPoint = (position: GeolocationPosition): Point => ({ clientGeneratedId: nanoid(16), latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, altitude: position.coords.altitude, heading: position.coords.heading, speed: position.coords.speed, recordedAt: new Date(position.timestamp).toISOString() });

export function DriverTrackingProvider({ children }: { children: React.ReactNode }) {
  const [session, setSession] = useState<Session | null>(null); const [tracking, setTracking] = useState(false); const [starting, setStarting] = useState(false); const [locationCount, setLocationCount] = useState(0); const [lastLocation, setLastLocation] = useState<{ lat: number; lng: number } | null>(null); const [error, setError] = useState<string | null>(null);
  const sessionRef = useRef<Session | null>(null); const watchRef = useRef<number | null>(null); const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null); const queueRef = useRef<Point[]>([]); const sendingRef = useRef(false);
  const setActiveSession = (value: Session | null) => { sessionRef.current = value; setSession(value); setTracking(Boolean(value)); };
  const stopWatcher = useCallback(() => { if (watchRef.current !== null) navigator.geolocation.clearWatch(watchRef.current); if (intervalRef.current) clearInterval(intervalRef.current); watchRef.current = null; intervalRef.current = null; }, []);
  const flush = useCallback(async () => { const current = sessionRef.current; if (!current || !queueRef.current.length || sendingRef.current) return; sendingRef.current = true; const points = queueRef.current.splice(0); try { const response = await fetch('/api/driver/tracking/location', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: current.id, locations: points }) }); if (!response.ok) queueRef.current.unshift(...points); } catch { queueRef.current.unshift(...points); } finally { sendingRef.current = false; } }, []);
  const beginWatch = useCallback(() => { if (watchRef.current !== null || !sessionRef.current || !navigator.geolocation) return; watchRef.current = navigator.geolocation.watchPosition((position) => { const point = toPoint(position); queueRef.current.push(point); setLastLocation({ lat: point.latitude, lng: point.longitude }); setLocationCount((count) => count + 1); if (queueRef.current.length >= 10) void flush(); }, () => setError('تعذر الحصول على موقعك حاليًا.'), { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 }); intervalRef.current = setInterval(() => { void flush(); }, 30000); }, [flush]);
  const restore = useCallback(async () => { try { const response = await fetch('/api/driver/tracking/session/start', { cache: 'no-store' }); const payload = await response.json(); if (response.ok && payload.data) { const active = payload.data as Session & { locationCount: number; lastLocation: { lat: number; lng: number } | null }; setActiveSession(active); setLocationCount(active.locationCount); setLastLocation(active.lastLocation); } } catch { setError('تعذر استعادة جلسة التتبع.'); } }, []);
  useEffect(() => { void restore(); return stopWatcher; }, [restore, stopWatcher]); useEffect(() => { if (tracking) beginWatch(); }, [tracking, beginWatch]);
  const startTracking = async () => { if (!navigator.geolocation) { setError('المتصفح لا يدعم تحديد الموقع.'); return; } setStarting(true); setError(null); try { const position = await new Promise<GeolocationPosition>((resolve, reject) => navigator.geolocation.getCurrentPosition(resolve, reject, { enableHighAccuracy: true, maximumAge: 0, timeout: 10000 })); const point = toPoint(position); const response = await fetch('/api/driver/tracking/session/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ deviceInfo: navigator.userAgent, initialLocation: point }) }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(); setActiveSession(payload.data as Session); setLocationCount(1); setLastLocation({ lat: point.latitude, lng: point.longitude }); } catch { setError('تعذر بدء التتبع. تحقق من إذن الموقع ثم أعد المحاولة.'); } finally { setStarting(false); } };
  const stopTracking = async (password: string) => { const current = sessionRef.current; if (!current) return { ok: true }; const response = await fetch('/api/driver/tracking/session/end', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ sessionId: current.id, masterPassword: password }) }); if (!response.ok) { const payload = await response.json().catch(() => ({})); return { ok: false, code: payload.code }; } stopWatcher(); await flush(); queueRef.current = []; setActiveSession(null); setLocationCount(0); setLastLocation(null); return { ok: true }; };
  return <Context.Provider value={{ session, tracking, starting, locationCount, lastLocation, error, startTracking, stopTracking, retryTracking: startTracking }}>{children}</Context.Provider>;
}
export function useDriverTracking() { const context = useContext(Context); if (!context) throw new Error('DriverTrackingProvider is required'); return context; }
