"use client";

import { useState } from "react";
import { Eye, EyeOff, MapPin, Play, Square } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useDriverTracking } from "@/components/driver/tracking-provider";

export default function DriverTrackingPage() {
  const { session, tracking, starting, locationCount, lastLocation, error, startTracking, stopTracking } = useDriverTracking();
  const [open, setOpen] = useState(false); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [stopping, setStopping] = useState(false); const [stopError, setStopError] = useState<string | null>(null);
  const close = () => { setOpen(false); setPassword(""); setShowPassword(false); setStopError(null); };
  const confirm = async () => { if (!password) { setStopError("أدخل كلمة مرور الإيقاف"); return; } setStopping(true); const result = await stopTracking(password); if (!result.ok) { const messages: Record<string, string> = { INCORRECT_PASSWORD: "كلمة مرور إيقاف التتبع غير صحيحة", TOO_MANY_ATTEMPTS: "تم تجاوز عدد المحاولات المسموح بها، حاول مرة أخرى لاحقًا", PASSWORD_REQUIRED: "أدخل كلمة مرور الإيقاف" }; setStopError(messages[result.code ?? ""] ?? "تعذر إيقاف التتبع حاليًا."); setPassword(""); setStopping(false); return; } close(); setStopping(false); };
  return <div className="space-y-6"><h1 className="text-2xl font-bold text-gray-900">التتبع</h1>{error && <Card className="border-red-200 bg-red-50"><CardContent className="p-4 text-sm text-red-800">{error}</CardContent></Card>}<Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-5 w-5" />حالة التتبع</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex justify-between"><span>الحالة</span><span>{tracking ? "جارٍ التتبع" : "غير نشط"}</span></div>{session && <><div className="flex justify-between"><span>بدأت في</span><span>{new Date(session.startedAt).toLocaleTimeString("ar-KW")}</span></div><div className="flex justify-between"><span>النقاط المرسلة</span><span>{locationCount}</span></div>{lastLocation && <p className="text-xs text-muted-foreground">آخر موقع: {lastLocation.lat.toFixed(6)}, {lastLocation.lng.toFixed(6)}</p>}</>}</CardContent></Card>{tracking ? <Button variant="destructive" className="h-14 w-full" onClick={() => setOpen(true)}><Square className="ms-2 h-5 w-5" />إيقاف التتبع</Button> : <Button className="h-14 w-full" disabled={starting} onClick={() => void startTracking()}><Play className="ms-2 h-5 w-5" />{starting ? "جارٍ التحقق من الموقع..." : "بدء التتبع"}</Button>}{open && <div className="fixed inset-0 z-50 flex items-end bg-black/50 p-4 sm:items-center sm:justify-center"><Card className="w-full max-w-md"><CardHeader><CardTitle>إيقاف التتبع</CardTitle></CardHeader><CardContent className="space-y-4"><div className="relative"><Input autoFocus type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="كلمة مرور الإيقاف" disabled={stopping} /><Button type="button" variant="ghost" size="sm" className="absolute end-1 top-1" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</Button></div>{stopError && <p className="text-sm text-destructive">{stopError}</p>}<div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={close} disabled={stopping}>إلغاء</Button><Button variant="destructive" onClick={() => void confirm()} disabled={stopping}>تأكيد الإيقاف</Button></div></CardContent></Card></div>}</div>;
}
