"use client";

import { useState } from "react";
import { Eye, EyeOff, MapPin, Play, Square } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useDriverTracking } from "@/components/driver/tracking-provider";
import { useLocale } from "@/components/providers/locale-provider";

export default function DriverTrackingPage() {
  const { session, tracking, starting, locationCount, lastLocation, error, startTracking, stopTracking } = useDriverTracking(); const { t, locale } = useLocale(); const numberLocale = locale === "en" ? "en-US" : "ar-KW";
  const [open, setOpen] = useState(false); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [stopping, setStopping] = useState(false); const [stopError, setStopError] = useState<string | null>(null);
  const close = () => { setOpen(false); setPassword(""); setShowPassword(false); setStopError(null); };
  const confirm = async () => { if (!password) { setStopError(t("driver.stopPasswordRequired")); return; } setStopping(true); const messages: Record<string, string> = { INCORRECT_PASSWORD: t("driver.incorrectStopPassword"), TOO_MANY_ATTEMPTS: t("driver.tooManyStopAttempts"), PASSWORD_REQUIRED: t("driver.stopPasswordRequired") }; const result = await stopTracking(password); if (!result.ok) { setStopError(messages[result.code ?? ""] ?? t("driver.stopTrackingFailed")); setPassword(""); setStopping(false); return; } close(); setStopping(false); };
  return <div className="space-y-6"><h1 className="text-2xl font-bold text-gray-900">{t("driver.tracking")}</h1>{error && <Card className="border-red-200 bg-red-50"><CardContent className="p-4 text-sm text-red-800">{error}</CardContent></Card>}<Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MapPin className="h-5 w-5" />{t("driver.trackingStatus")}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex justify-between"><span>{t("driver.status")}</span><span>{tracking ? t("driver.trackingActive") : t("driver.inactive")}</span></div>{session && <><div className="flex justify-between"><span>{t("driver.startedAt")}</span><span>{new Date(session.startedAt).toLocaleTimeString(numberLocale)}</span></div><div className="flex justify-between"><span>{t("driver.pointsSent")}</span><span>{locationCount.toLocaleString(numberLocale)}</span></div>{lastLocation && <p className="text-xs text-muted-foreground">{t("driver.lastLocation")}: {lastLocation.lat.toFixed(6)}, {lastLocation.lng.toFixed(6)}</p>}</>}</CardContent></Card>{tracking ? <Button variant="destructive" className="h-14 w-full" onClick={() => setOpen(true)}><Square className="ms-2 h-5 w-5" />{t("driver.stopTracking")}</Button> : <Button className="h-14 w-full" disabled={starting} onClick={() => void startTracking()}><Play className="ms-2 h-5 w-5" />{starting ? t("driver.checkingLocation") : t("driver.startTracking")}</Button>}{open && <div className="fixed inset-0 z-50 flex items-end bg-black/50 p-4 sm:items-center sm:justify-center"><Card className="w-full max-w-md"><CardHeader><CardTitle>{t("driver.stopTracking")}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="relative"><Input autoFocus type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} placeholder={t("driver.stopPassword")} disabled={stopping} /><Button type="button" variant="ghost" size="sm" className="absolute end-1 top-1" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</Button></div>{stopError && <p className="text-sm text-destructive">{stopError}</p>}<div className="grid grid-cols-2 gap-3"><Button variant="outline" onClick={close} disabled={stopping}>{t("driver.cancel")}</Button><Button variant="destructive" onClick={() => void confirm()} disabled={stopping}>{t("driver.confirmStop")}</Button></div></CardContent></Card></div>}</div>;
}
