ALTER TABLE user_company_access ADD COLUMN id VARCHAR(191) NULL;
ALTER TABLE user_company_access ADD COLUMN roleId VARCHAR(191) NULL;
ALTER TABLE user_company_access ADD COLUMN canView TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE user_company_access ADD COLUMN canCreate TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_company_access ADD COLUMN canUpdate TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_company_access ADD COLUMN canDelete TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_company_access ADD COLUMN canApprove TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE user_company_access ADD COLUMN updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
UPDATE user_company_access
SET id = CONCAT('uca_', REPLACE(UUID(), '-', ''))
WHERE id IS NULL OR id = '';
ALTER TABLE user_company_access MODIFY COLUMN id VARCHAR(191) NOT NULL;
