"use client";

import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { Camera, Upload } from "lucide-react";
import { readInvoiceImage } from "@/lib/delivery/invoice-ocr";
import { useLocale } from "@/components/providers/locale-provider";

function extractReceiptFields(text: string) {
  const amount = /(?:total\s*amount|إجمالي\s*المبلغ)[^\d]*(\d[\d,]*\.\d{3})/i.exec(text)?.[1]?.replace(/,/g, "");
  const date = /(?:date|التاريخ)[^\d]*(\d{2}[/-]\d{2}[/-]\d{2,4})/i.exec(text)?.[1];
  const reference = /(?:transaction\s*(?:id|no)|رقم\s*الحركة)[^\d]*(\d{3,})/i.exec(text)?.[1];
  const normalizedDate = date ? (() => { const [day, month, year] = date.replace(/-/g, "/").split("/"); return `${year.length === 2 ? `20${year}` : year}-${month}-${day}`; })() : "";
  return { amount: amount ?? "", date: normalizedDate, reference: reference ?? "" };
}

export function PartnerDepositForm({ onSaved }: { onSaved: () => void }) {
  const { locale } = useLocale(); const en = locale === "en"; const t = (ar: string, english: string) => en ? english : ar;
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null); const [form, setForm] = useState({ transactionDate: "", amount: "", transactionReference: "", notes: "" }); const [ocrText, setOcrText] = useState(""); const [reading, setReading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function selectFile(event: ChangeEvent<HTMLInputElement>) { const next = event.target.files?.[0]; if (!next) return; if (preview) URL.revokeObjectURL(preview); setFile(next); setPreview(URL.createObjectURL(next)); setError(""); setReading(true); try { const result = await readInvoiceImage(next); const found = extractReceiptFields(result.text); setOcrText(result.text); setForm((current) => ({ ...current, amount: found.amount || current.amount, transactionDate: found.date || current.transactionDate, transactionReference: found.reference || current.transactionReference })); } catch { setError(t("تعذر قراءة الإيصال تلقائياً؛ أدخل البيانات يدوياً.", "Could not read the receipt automatically; enter the details manually.")); } finally { setReading(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!file || !form.transactionDate || !form.amount) { setError(t("ارفع الإيصال وأدخل التاريخ والمبلغ.", "Upload the receipt and enter its date and amount.")); return; } setSaving(true); setError(""); try { const data = new FormData(); data.append("file", file); Object.entries(form).forEach(([key, value]) => value && data.append(key, value)); if (ocrText) data.append("ocrRawText", ocrText); const response = await fetch("/api/owner-management/partner/revenues", { method: "POST", body: data }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || "Save failed"); if (preview) URL.revokeObjectURL(preview); setFile(null); setPreview(null); setOcrText(""); setForm({ transactionDate: "", amount: "", transactionReference: "", notes: "" }); if (input.current) input.current.value = ""; onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("تعذر الحفظ.", "Unable to save.")); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="section-card space-y-4" dir={en ? "ltr" : "rtl"}><div><h2 className="font-bold">{t("رفع إيصال إيداع", "Upload deposit receipt")}</h2><p className="text-sm text-muted-foreground">{t("ستتم محاولة استخراج البيانات تلقائياً؛ راجعها قبل الحفظ.", "Details are read automatically when possible; review them before saving.")}</p></div><input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={selectFile} /><button type="button" onClick={() => input.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-lg border border-dashed p-5"><Camera size={18} />{file ? t("تغيير صورة الإيصال", "Change receipt image") : t("التقاط أو اختيار الإيصال", "Take or choose receipt")}</button>{preview && <img src={preview} alt="receipt" className="max-h-64 w-full rounded border object-contain" />}{reading && <p className="text-sm text-muted-foreground">{t("جارٍ قراءة الإيصال…", "Reading receipt…")}</p>}<div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">{t("تاريخ الإيداع", "Deposit date")}<input required type="date" value={form.transactionDate} onChange={(e) => setForm({ ...form, transactionDate: e.target.value })} className="input-field" /></label><label className="grid gap-1 text-sm">{t("المبلغ (KWD)", "Amount (KWD)")}<input required type="number" min="0.001" step="0.001" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} className="input-field" dir="ltr" /></label><label className="grid gap-1 text-sm sm:col-span-2">{t("رقم الحركة", "Transaction ID")}<input value={form.transactionReference} onChange={(e) => setForm({ ...form, transactionReference: e.target.value })} className="input-field" dir="ltr" /></label><label className="grid gap-1 text-sm sm:col-span-2">{t("ملاحظات", "Notes")}<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className="input-field min-h-20" /></label></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={saving || reading} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50"><Upload size={16} />{saving ? t("جارٍ الحفظ…", "Saving…") : t("حفظ الإيراد", "Save revenue")}</button></form>;
}
