import Link from "next/link";
import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/auth/session";
import { getPartnerFromSession } from "@/lib/owner-management/access";
import { prisma } from "@/lib/db";
const PAGE_SIZE = 25; const date = (value?: string) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T00:00:00.000Z`) : undefined;
export default async function PartnerRevenuesPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; page?: string }> }) {
  const search = await searchParams; const session = await getSession(); if (!session) redirect("/login"); const partner = await getPartnerFromSession(session); if (!partner) redirect("/dashboard"); const from = date(search.from), to = date(search.to); if (to) to.setUTCHours(23, 59, 59, 999); const page = Math.max(1, Number(search.page) || 1); const where: Prisma.OwnerManagedRevenueWhereInput = { partnerId: partner.id, status: "MATCHED", ...(from || to ? { transactionDate: { ...(from ? { gte: from } : {}), ...(to ? { lte: to } : {}) } } : {}) }; const [rows, total, aggregate] = await Promise.all([prisma.ownerManagedRevenue.findMany({ where, orderBy: [{ transactionDate: "desc" }, { createdAt: "desc" }], skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE }), prisma.ownerManagedRevenue.count({ where }), prisma.ownerManagedRevenue.aggregate({ where, _sum: { amount: true } })]); const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const query = new URLSearchParams(); if (search.from) query.set("from", search.from); if (search.to) query.set("to", search.to); const href = (next: number) => `?${new URLSearchParams({ ...Object.fromEntries(query), page: String(next) })}`;
  return <main dir="rtl" className="min-h-screen bg-muted/30 p-4 md:p-8"><section className="mx-auto max-w-4xl space-y-5"><header><h1 className="text-2xl font-bold">إيراداتي</h1><p className="text-muted-foreground">إجمالي الفترة: {Number(aggregate._sum.amount ?? 0).toFixed(3)} د.ك</p></header><form className="section-card flex flex-wrap gap-3"><label>من<input className="ms-2 rounded border p-2" name="from" type="date" defaultValue={search.from} /></label><label>إلى<input className="ms-2 rounded border p-2" name="to" type="date" defaultValue={search.to} /></label><button className="rounded bg-primary px-4 py-2 text-primary-foreground">تصفية</button></form><div className="section-card overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b"><th>التاريخ</th><th>المرجع</th><th>المبلغ</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-b"><td>{row.transactionDate?.toLocaleDateString("en-CA")}</td><td dir="ltr">{row.transactionReference}</td><td>{Number(row.amount).toFixed(3)}</td></tr>) : <tr><td colSpan={3} className="p-6 text-center text-muted-foreground">لا توجد إيرادات للفترة.</td></tr>}</tbody></table></div><nav className="flex justify-between"><Link className="rounded border px-3 py-2" href={page > 1 ? href(page - 1) : href(1)}>السابق</Link><span>صفحة {page} من {pages}</span><Link className="rounded border px-3 py-2" href={page < pages ? href(page + 1) : href(pages)}>التالي</Link></nav><Link className="text-primary underline" href="/partner">العودة للبوابة</Link></section></main>;
}
