"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Eye } from "lucide-react";
import { useLocale } from "@/components/providers/locale-provider";
import { PartnerDepositForm } from "@/components/owner-management/partner-deposit-form";
type Revenue = { id: string; transactionDate: string | null; transactionReference: string | null; amount: string | number; description: string; receiptImageUrl: string | null };
export default function PartnerRevenuesPage() {
  const { locale } = useLocale(); const en = locale === "en"; const t = (ar: string, english: string) => en ? english : ar;
  const [rows, setRows] = useState<Revenue[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/owner-management/partner/revenues", { cache: "no-store" }); const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload.error || "Unable to load revenues"); setRows(payload.data ?? []); } catch { setError(t("تعذر تحميل الإيرادات.", "Unable to load revenues.")); } finally { setLoading(false); } }, [en]);
  useEffect(() => { void load(); }, [load]);
  const total = rows.reduce((sum, row) => sum + Number(row.amount), 0);
  return <main dir={en ? "ltr" : "rtl"} className="min-h-screen bg-muted/30 p-4 md:p-8"><section className="mx-auto max-w-4xl space-y-6"><header><h1 className="text-2xl font-bold">{t("إيراداتي", "My revenues")}</h1><p className="text-sm text-muted-foreground">{t("إجمالي الإيرادات", "Total revenues")}: {total.toFixed(3)} KWD</p></header><PartnerDepositForm onSaved={() => void load()} />{error && <p className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}<section className="section-card overflow-x-auto"><h2 className="mb-3 font-bold">{t("الإيداعات السابقة", "Previous deposits")}</h2><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-2">{t("التاريخ", "Date")}</th><th className="p-2">{t("المرجع", "Reference")}</th><th className="p-2">{t("المبلغ", "Amount")}</th><th className="p-2">{t("الإيصال", "Receipt")}</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-5 text-center">{t("جارٍ التحميل…", "Loading…")}</td></tr> : rows.length ? rows.map((row) => <tr key={row.id} className="border-b"><td className="p-2">{row.transactionDate ? new Date(row.transactionDate).toLocaleDateString("en-CA") : "—"}</td><td className="p-2" dir="ltr">{row.transactionReference ?? "—"}</td><td className="p-2" dir="ltr">{Number(row.amount).toFixed(3)}</td><td className="p-2">{row.receiptImageUrl ? <a href={row.receiptImageUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary underline"><Eye size={15} />{t("عرض", "View")}</a> : "—"}</td></tr>) : <tr><td colSpan={4} className="p-5 text-center text-muted-foreground">{t("لا توجد إيرادات بعد.", "No revenues yet.")}</td></tr>}</tbody></table></section><Link className="text-primary underline" href="/partner">{t("العودة للبوابة", "Back to portal")}</Link></section></main>;
}
