"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Trash2 } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { useLocale } from "@/components/providers/locale-provider";

interface SessionRow { id: string; status: "ACTIVE" | "PAUSED" | "ENDED"; startedAt: string; endedAt: string | null; pointCount: number; }
interface Payload { success: boolean; data: { driver: { id: string; nameAr: string; nameEn: string | null; accountType: string; accountActive: boolean }; latestLocation: { latitude: number; longitude: number; recordedAt: string } | null; activeSession: { id: string; startedAt: string } | null; totalSessions: number; totalPoints: number; sessions: SessionRow[] }; pagination: { page: number; totalPages: number; total: number }; }
type DeleteTarget = { kind: "one"; ids: string[] } | { kind: "bulk"; ids: string[] } | { kind: "all"; ids: string[] } | null;

export function DriverTrackingDriverDetail({ companyId, driverId, canDelete }: { companyId: string; driverId: string; canDelete: boolean }) {
  const { locale } = useLocale(); const en = locale === "en"; const [payload, setPayload] = useState<Payload | null>(null); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [target, setTarget] = useState<DeleteTarget>(null); const [confirmation, setConfirmation] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/companies/${companyId}/driver-tracking/drivers/${driverId}?page=${page}`, { cache: "no-store" }); const result = await response.json() as Payload; if (!response.ok || !result.success) throw new Error(en ? "Unable to load driver tracking history." : "تعذر تحميل سجل تتبّع السائق."); setPayload(result); setSelected([]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Error"); } finally { setLoading(false); } }, [companyId, driverId, en, page]);
  useEffect(() => { void load(); }, [load]);
  const date = (value: string | null) => value ? new Date(value).toLocaleString(en ? "en-US" : "ar-KW") : "—";
  const duration = (item: SessionRow) => { if (!item.endedAt) return "—"; const minutes = Math.max(0, Math.round((new Date(item.endedAt).getTime() - new Date(item.startedAt).getTime()) / 60_000)); return `${minutes} ${en ? "min" : "د"}`; };
  async function deleteRecords() { if (!target || (target.kind !== "one" && confirmation !== "DELETE")) return; setError(""); const base = `/api/companies/${companyId}/driver-tracking`; const url = target.kind === "one" ? `${base}/sessions/${target.ids[0]}` : target.kind === "bulk" ? `${base}/sessions/bulk-delete` : `${base}/drivers/${driverId}/sessions`; const response = await fetch(url, target.kind === "one" ? { method: "DELETE" } : { method: target.kind === "bulk" ? "POST" : "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify(target.kind === "bulk" ? { sessionIds: target.ids, confirmation: "DELETE" } : { confirmation: "DELETE" }) }); const result = await response.json() as { success?: boolean; error?: string }; if (!response.ok || !result.success) { setError(result.error ?? (en ? "Deletion failed." : "فشل الحذف.")); return; } setTarget(null); setConfirmation(""); if (payload && page > 1 && payload.data.sessions.length === target.ids.length) setPage((value) => value - 1); else void load(); }
  if (loading) return <p className="py-8 text-sm text-muted-foreground">{en ? "Loading driver history..." : "جارٍ تحميل سجل السائق..."}</p>;
  if (!payload) return <p className="py-8 text-sm text-destructive">{error}</p>;
  const { data, pagination } = payload; const name = en ? data.driver.nameEn ?? data.driver.nameAr : data.driver.nameAr; const allSelected = data.sessions.length > 0 && data.sessions.every((item) => selected.includes(item.id));
  return <div className="space-y-4"><Card><CardContent className="grid gap-4 p-5 text-sm sm:grid-cols-2 xl:grid-cols-4"><div><p className="text-muted-foreground">{en ? "Driver" : "السائق"}</p><p className="font-medium">{name}</p></div><div><p className="text-muted-foreground">{en ? "Account" : "الحساب"}</p><p className="font-medium">{data.driver.accountActive ? (en ? "Active" : "نشط") : (en ? "Inactive" : "غير نشط")}</p></div><div><p className="text-muted-foreground">{en ? "Latest location" : "آخر موقع"}</p><p className="font-medium" dir="ltr">{data.latestLocation ? `${data.latestLocation.latitude.toFixed(5)}, ${data.latestLocation.longitude.toFixed(5)}` : "—"}</p></div><div><p className="text-muted-foreground">{en ? "Last update" : "آخر تحديث"}</p><p className="font-medium">{date(data.latestLocation?.recordedAt ?? null)}</p></div><div><p className="text-muted-foreground">{en ? "Sessions" : "الجلسات"}</p><p className="font-medium">{data.totalSessions}</p></div><div><p className="text-muted-foreground">{en ? "Total points" : "إجمالي النقاط"}</p><p className="font-medium">{data.totalPoints}</p></div><div><p className="text-muted-foreground">{en ? "Tracking status" : "حالة التتبّع"}</p><p className="font-medium">{data.activeSession ? (en ? "Active" : "نشط") : (en ? "Inactive" : "غير نشط")}</p></div><div><p className="text-muted-foreground">{en ? "Active session" : "الجلسة النشطة"}</p><p className="font-medium">{date(data.activeSession?.startedAt ?? null)}</p></div></CardContent></Card>
    {canDelete && <div className="flex flex-wrap justify-end gap-2">{selected.length > 0 && <button onClick={() => setTarget({ kind: "bulk", ids: selected })} className="rounded border border-red-200 px-3 py-2 text-sm text-red-600">{en ? "Delete selected" : "حذف المحدد"} ({selected.length})</button>}<button onClick={() => setTarget({ kind: "all", ids: data.sessions.map((item) => item.id) })} className="rounded border border-red-200 px-3 py-2 text-sm text-red-600">{en ? "Delete all tracking records" : "حذف جميع سجلات التتبّع"}</button></div>}
    <Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/50 text-muted-foreground"><tr>{canDelete && <th className="px-4 py-3"><input type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? [] : data.sessions.map((item) => item.id))} /></th>}<th className="px-4 py-3 text-start">{en ? "Date" : "التاريخ"}</th><th className="px-4 py-3 text-start">{en ? "Status" : "الحالة"}</th><th className="px-4 py-3 text-start">{en ? "Points" : "النقاط"}</th><th className="px-4 py-3 text-start">{en ? "Duration" : "المدة"}</th><th className="px-4 py-3 text-start">{en ? "Actions" : "الإجراءات"}</th></tr></thead><tbody>{data.sessions.map((item) => <tr key={item.id} className="border-t"><td className="px-4 py-3">{canDelete && <input type="checkbox" disabled={item.status === "ACTIVE"} checked={selected.includes(item.id)} onChange={() => setSelected((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} />}</td><td className="px-4 py-3">{date(item.startedAt)}</td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3">{item.pointCount}</td><td className="px-4 py-3">{duration(item)}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/dashboard/companies/${companyId}/driver-tracking/sessions/${item.id}`} className="rounded border px-2 py-1">{en ? "Route" : "المسار"}</Link>{canDelete && item.status !== "ACTIVE" && <button onClick={() => setTarget({ kind: "one", ids: [item.id] })} className="rounded p-1 text-red-600"><Trash2 className="h-4 w-4" /></button>}</div></td></tr>)}</tbody></table></CardContent></Card><div className="flex justify-between text-sm"><span>{pagination.total} {en ? "sessions" : "جلسة"}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded border px-3 py-1 disabled:opacity-50">{en ? "Previous" : "السابق"}</button><span>{pagination.page}/{pagination.totalPages}</span><button disabled={page >= pagination.totalPages} onClick={() => setPage((value) => value + 1)} className="rounded border px-3 py-1 disabled:opacity-50">{en ? "Next" : "التالي"}</button></div></div>
    {target && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md space-y-4 rounded-xl bg-card p-5 shadow-xl"><h2 className="font-semibold text-red-600">{en ? "Confirm deletion" : "تأكيد الحذف"}</h2><p className="text-sm text-muted-foreground">{target.kind === "one" ? (en ? "This tracking session and its points will be permanently deleted." : "سيتم حذف جلسة التتبّع ونقاطها نهائيًا.") : (en ? "Type DELETE to permanently remove the selected tracking records. Active sessions cannot be deleted." : "اكتب DELETE لحذف سجلات التتبّع المحددة نهائيًا. لا يمكن حذف الجلسات النشطة.")}</p>{target.kind !== "one" && <input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder="DELETE" className="w-full rounded border px-3 py-2" />}{error && <p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><button onClick={() => { setTarget(null); setConfirmation(""); }} className="rounded border px-3 py-2">{en ? "Cancel" : "إلغاء"}</button><button disabled={target.kind !== "one" && confirmation !== "DELETE"} onClick={() => void deleteRecords()} className="rounded bg-red-600 px-3 py-2 text-white disabled:opacity-50">{en ? "Delete" : "حذف"}</button></div></div></div>}</div>;
}
