"use client";
import { useEffect, useRef, useState } from "react";
import { readInvoiceImage } from "@/lib/delivery/invoice-ocr";
import { useLocale } from "@/components/providers/locale-provider";

type Data = { vehicles: Array<{ id: string; code: string; nameAr: string; nameEn: string | null }>; categories: Array<{ id: string; nameAr: string; nameEn: string | null; type: string; code: string | null }> };
export function PortalMovementForm({ expense }: { expense: boolean }) {
 const { locale } = useLocale(); const en = locale === "en"; const txt = (ar:string, english:string)=>en?english:ar;
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[ok,setOk]=useState(""),[saving,setSaving]=useState(false),[preview,setPreview]=useState<string|null>(null),[reading,setReading]=useState(false);
 const [form,setForm]=useState({vehicleId:"",categoryId:"",kind:"CASH",date:new Date().toISOString().slice(0,10),amount:"",notes:"",transactionReference:""}); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/api/car-wash-portal/form-data").then(r=>r.json()).then(p=>{if(!p.success)throw Error(p.error);setData(p.data); if(p.data.vehicles.length===1)setForm(f=>({...f,vehicleId:p.data.vehicles[0].id}));}).catch(e=>setError(e.message));},[]);
 async function image(file?:File){if(!file)return;if(!file.type.startsWith("image/")||file.size>10*1024*1024){setError(txt("الصورة غير صالحة أو كبيرة","Invalid or oversized image"));return;}setPreview(URL.createObjectURL(file));setReading(true);try{const result=await readInvoiceImage(file);setForm(f=>({...f,amount:result.amount?.toFixed(3)??f.amount,date:result.date??f.date,notes:f.notes||result.merchantName||""}));}catch{setError(txt("تعذرت قراءة الصورة","OCR could not read the image"));}finally{setReading(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setOk("");if(!form.vehicleId||!form.amount||(expense&&!form.categoryId)){setError(txt("أكمل الحقول المطلوبة","Complete required fields"));return;}setSaving(true);try{const r=await fetch("/api/car-wash-portal/movements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:expense?"EXPENSE":form.kind,vehicleId:form.vehicleId,categoryId:expense?form.categoryId:undefined,amount:Number(form.amount),date:form.date,notes:form.notes,transactionReference:form.transactionReference||undefined})});const p=await r.json();if(!r.ok)throw Error(p.error);setOk(txt("تم حفظ الحركة","Movement saved"));setForm(f=>({...f,amount:"",notes:"",transactionReference:""}));setPreview(null);}catch(e){setError(e instanceof Error?e.message:txt("فشل الحفظ","Save failed"));}finally{setSaving(false)}}
 if(!data)return <p>{error||txt("جاري التحميل...","Loading...")}</p>;
 const category=data.categories.find(c=>c.id===form.categoryId); const water=category?.type.toLowerCase()==="water"||category?.code?.toLowerCase()==="water";
 return <form onSubmit={submit} className="space-y-4 rounded-xl border bg-white p-4" dir={en?"ltr":"rtl"}>{error&&<p className="text-red-600">{error}</p>}{ok&&<p className="text-green-600">{ok}</p>}<label>{txt("السيارة","Vehicle")}<select required value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})} className="input-field w-full"><option value="">{txt("اختر","Select")}</option>{data.vehicles.map(v=><option key={v.id} value={v.id}>{v.code} — {en?v.nameEn??v.nameAr:v.nameAr}</option>)}</select></label>{expense?<label>{txt("نوع المصروف","Expense type")}<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} className="input-field w-full"><option value="">{txt("اختر","Select")}</option>{data.categories.map(c=><option key={c.id} value={c.id}>{en?c.nameEn??c.nameAr:c.nameAr}</option>)}</select></label>:<label>{txt("نوع الإيراد","Revenue type")}<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})} className="input-field w-full"><option value="CASH">CASH</option><option value="KNET">KNET</option></select></label>}<label>{txt("التاريخ","Date")}<input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="input-field w-full"/></label><label>{txt("المبلغ","Amount")}<input required type="number" step="0.001" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="input-field w-full"/></label>{!expense&&form.kind==="KNET"&&<label>{txt("مرجع العملية","Transaction reference")}<input value={form.transactionReference} onChange={e=>setForm({...form,transactionReference:e.target.value})} className="input-field w-full"/></label>}<label>{txt("ملاحظات","Notes")}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="input-field w-full"/></label>{(!expense||!water)&&<><input ref={input} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>image(e.target.files?.[0])}/><button type="button" onClick={()=>input.current?.click()} className="w-full rounded border p-3">{txt("التقاط أو اختيار صورة","Take or choose image")}</button>{preview&&<img src={preview} alt="preview" className="max-h-56 w-full rounded object-contain"/>}{reading&&<p>{txt("جاري قراءة الصورة...","Reading image...")}</p>}</>}<button disabled={saving||reading} className="w-full rounded bg-primary p-3 text-primary-foreground">{saving?txt("جارٍ الحفظ...","Saving..."):txt("حفظ","Save")}</button></form>;
}
