import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { requireRequestSession } from "@/lib/auth/access";
import { forbidden, requireOwnerManagedCompany } from "@/lib/owner-management/access";
import { normalizeMid } from "@/lib/owner-management/nbk-parser";

const patchSchema = z.object({ name: z.string().min(2).optional(), phone: z.string().nullable().optional(), email: z.string().email().nullable().optional(), mid: z.string().optional(), isActive: z.boolean().optional() });
async function access(request: NextRequest, params: Promise<{ companyId: string; partnerId: string }>) { const session=await requireRequestSession(request); if(session instanceof NextResponse)return [null,null,null] as const; const {companyId,partnerId}=await params; if(!await requireOwnerManagedCompany(session,companyId))return [session,null,null] as const; return [session,companyId,await prisma.ownerManagedPartner.findFirst({where:{id:partnerId,companyId}})] as const; }
export async function PATCH(request: NextRequest,{params}:{params:Promise<{companyId:string;partnerId:string}>}) { const [session,companyId,partner]=await access(request,params); if(!session||!companyId||!partner)return forbidden(); const parsed=patchSchema.safeParse(await request.json()); if(!parsed.success)return NextResponse.json({success:false,error:"Invalid partner data"},{status:400}); const body=parsed.data; const mid=body.mid===undefined?undefined:normalizeMid(body.mid); if(body.mid!==undefined&&!mid)return NextResponse.json({success:false,error:"Invalid MID"},{status:400}); if(mid&&mid!==partner.mid&&await prisma.ownerManagedPartner.findFirst({where:{companyId,mid,NOT:{id:partner.id}},select:{id:true}}))return NextResponse.json({success:false,error:"MID already exists for this company"},{status:409}); const updated=await prisma.$transaction(async tx=>{const row=await tx.ownerManagedPartner.update({where:{id:partner.id},data:{...body,mid:mid ?? undefined}}); await tx.auditLog.create({data:{userId:session.id,companyId,action:"UPDATE_OWNER_MANAGED_PARTNER",module:"owner_management",resourceId:row.id,resourceType:"OwnerManagedPartner"}});return row}); return NextResponse.json({success:true,data:updated}); }
export async function DELETE(request:NextRequest,{params}:{params:Promise<{companyId:string;partnerId:string}>}) { const [session,companyId,partner]=await access(request,params); if(!session||!companyId||!partner)return forbidden(); const [expenses,revenues]=await Promise.all([prisma.ownerManagedExpense.count({where:{partnerId:partner.id,deletedAt:null}}),prisma.ownerManagedRevenue.count({where:{partnerId:partner.id,status:{not:"VOIDED"}}})]); if(expenses||revenues){const row=await prisma.ownerManagedPartner.update({where:{id:partner.id},data:{isActive:false}}); await prisma.auditLog.create({data:{userId:session.id,companyId,action:"DEACTIVATE_OWNER_MANAGED_PARTNER",module:"owner_management",resourceId:row.id,resourceType:"OwnerManagedPartner"}});return NextResponse.json({success:true,data:row,deactivated:true,reason:"Partner has linked movements"});} await prisma.$transaction(async tx=>{await tx.ownerManagedPartner.delete({where:{id:partner.id}});await tx.auditLog.create({data:{userId:session.id,companyId,action:"DELETE_OWNER_MANAGED_PARTNER",module:"owner_management",resourceId:partner.id,resourceType:"OwnerManagedPartner"}})});return NextResponse.json({success:true}); }
