import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db";
import { Prisma } from "@prisma/client";
import { requireRequestSession } from "@/lib/auth/access";
import { forbidden, requireOwnerManagedCompany } from "@/lib/owner-management/access";
const input=z.object({invoiceDate:z.string().datetime().optional(),amount:z.number().positive().optional(),notes:z.string().max(10000).nullable().optional(),imageUrl:z.string().url().nullable().optional()});
async function base(request:NextRequest,params:Promise<{companyId:string;expenseId:string}>){const s=await requireRequestSession(request);if(s instanceof NextResponse)return [null,null,null]as const;const {companyId,expenseId}=await params;if(!await requireOwnerManagedCompany(s,companyId))return[s,null,null]as const;return[s,companyId,await prisma.ownerManagedExpense.findFirst({where:{id:expenseId,companyId,deletedAt:null}})]as const;}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{companyId:string;expenseId:string}>}){const[s,c,row]=await base(request,params);if(!s||!c||!row)return forbidden();const p=input.safeParse(await request.json());if(!p.success)return NextResponse.json({success:false,error:"Invalid expense data"},{status:400});const updated=await prisma.$transaction(async tx=>{const x=await tx.ownerManagedExpense.update({where:{id:row.id},data:{...p.data,invoiceDate:p.data.invoiceDate?new Date(p.data.invoiceDate):undefined,amount:p.data.amount===undefined?undefined:new Prisma.Decimal(p.data.amount)}});await tx.auditLog.create({data:{userId:s.id,companyId:c,action:"UPDATE_OWNER_MANAGED_EXPENSE",module:"owner_management",resourceId:x.id,resourceType:"OwnerManagedExpense"}});return x});return NextResponse.json({success:true,data:updated});}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{companyId:string;expenseId:string}>}){const[s,c,row]=await base(request,params);if(!s||!c||!row)return forbidden();await prisma.$transaction(async tx=>{await tx.ownerManagedExpense.update({where:{id:row.id},data:{deletedAt:new Date()}});await tx.auditLog.create({data:{userId:s.id,companyId:c,action:"SOFT_DELETE_OWNER_MANAGED_EXPENSE",module:"owner_management",resourceId:row.id,resourceType:"OwnerManagedExpense"}})});return NextResponse.json({success:true});}
